language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

env:
    matrix:
        - DEPS=high
        - DEPS=low

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - nightly
    - hhvm
    - hhvm-nightly

matrix:
    allow_failures:
        - php: nightly
        - php: hhvm
        - php: hhvm-nightly
    fast_finish: true

before_script:
    - export DISPLAY=:99.0 GECKO_DRIVER_VERSION=0.19.1 SELENIUM_VERSION=3.6.0
    - Xvfb $DISPLAY -extension RANDR &> /dev/null &

    - wget "https://github.com/mozilla/geckodriver/releases/download/v${GECKO_DRIVER_VERSION}/geckodriver-v${GECKO_DRIVER_VERSION}-linux64.tar.gz"
    - tar xf geckodriver-v${GECKO_DRIVER_VERSION}-linux64.tar.gz
    - wget "https://selenium-release.storage.googleapis.com/${SELENIUM_VERSION%%.[[:digit:]]}/selenium-server-standalone-${SELENIUM_VERSION}.jar" -O selenium.jar
    - java -jar -Dwebdriver.gecko.driver=./geckodriver selenium.jar &> /dev/null &

    - php -S localhost:8080 -t tests/fixtures/www &> /dev/null &
    - cp behat.yml{.dist,}
    - composer install

    - test "$DEPS" == "low" || composer update --prefer-lowest
    - test "$DEPS" == "high" || composer update atoum/atoum

script:
    - ./bin/atoum
    - ./bin/behat -fprogress --tags='~@user' --no-interaction
    - ./bin/behat -fprogress --tags='~@user' --no-interaction --profile=symfony2
