language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - nightly
    - hhvm
    - hhvm-nightly

matrix:
    allow_failures:
        - php: nightly
        - php: hhvm
        - php: hhvm-nightly
    fast_finish: true

before_script:
    - export DISPLAY=:99.0
    - Xvfb $DISPLAY -extension RANDR &> /dev/null &

    - wget "https://selenium-release.storage.googleapis.com/3.6/selenium-server-standalone-3.6.0.jar" -O selenium.jar
    - java -jar selenium.jar -enablePassThrough false &> /dev/null &

    - php -S localhost:8080 -t tests/fixtures/www &> /dev/null &
    - cp behat.yml{.dist,}
    - composer install

script:
    - ./bin/atoum
    - ./bin/behat -fprogress --tags='~@user' --no-interaction
    - ./bin/behat -fprogress --tags='~@user' --no-interaction --profile=symfony2
